---
# Azure Indirect Node Counting Test Playbook (Expanded)
# Uses only FREE resources for testing indirect node counting
#
# FREE Azure Resources used:
#   - Resource Groups
#   - Virtual Networks (free, pay only for data transfer)
#   - Subnets (free, part of VNet)
#   - Network Security Groups (free)
#   - Network Security Group Rules (free)
#   - Route Tables (free)
#   - Application Security Groups (free)
#   - Availability Sets (free)
#   - Proximity Placement Groups (free)
#
# Prerequisites:
#   - azure.azcollection installed
#
# Usage:
#   ansible-playbook azure_indirect_node_test.yml -e @azure_creds.yml
#   ansible-playbook azure_indirect_node_test.yml -e cleanup=true -e @azure_creds.yml

- name: Azure Indirect Node Counting Test (Expanded)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    resource_group_name: "aap-indirect-node-test-rg"
    location: "eastus"
    cleanup: false
    
    # Resource naming
    vnet_name: "aap-test-vnet"
    nsg_names:
      - "nsg-web"
      - "nsg-app"
      - "nsg-db"
    route_table_name: "aap-test-routes"
    asg_names:
      - "asg-webservers"
      - "asg-appservers"
      - "asg-databases"
    availability_set_names:
      - "avset-web"
      - "avset-app"
    ppg_name: "aap-test-ppg"

  tasks:
    # =========================================
    # RESOURCE GROUP (FREE)
    # =========================================
    
    - name: Create resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ location }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
        tags:
          environment: "test"
          purpose: "aap-indirect-node-counting"
      register: rg_result

    # =========================================
    # VIRTUAL NETWORK + SUBNETS (FREE)
    # =========================================

    - name: Create virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vnet_name }}"
        address_prefixes_cidr:
          - "10.0.0.0/16"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
        tags:
          environment: "test"
      register: vnet_result

    - name: Create subnets
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ resource_group_name }}"
        virtual_network_name: "{{ vnet_name }}"
        name: "{{ item.name }}"
        address_prefix_cidr: "{{ item.cidr }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      loop:
        - { name: "subnet-web", cidr: "10.0.1.0/24" }
        - { name: "subnet-app", cidr: "10.0.2.0/24" }
        - { name: "subnet-db", cidr: "10.0.3.0/24" }
      register: subnet_results

    # =========================================
    # NETWORK SECURITY GROUPS (FREE)
    # =========================================

    - name: Create network security groups
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ resource_group_name }}"
        name: "{{ item }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
        tags:
          environment: "test"
      loop: "{{ nsg_names }}"
      register: nsg_results

    - name: Add NSG rules to web NSG
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ resource_group_name }}"
        name: "nsg-web"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
        rules:
          - name: "AllowHTTP"
            priority: 100
            direction: Inbound
            access: Allow
            protocol: Tcp
            destination_port_range: 80
            source_address_prefix: "*"
            destination_address_prefix: "*"
          - name: "AllowHTTPS"
            priority: 110
            direction: Inbound
            access: Allow
            protocol: Tcp
            destination_port_range: 443
            source_address_prefix: "*"
            destination_address_prefix: "*"

    # =========================================
    # APPLICATION SECURITY GROUPS (FREE)
    # =========================================

    - name: Create application security groups
      azure.azcollection.azure_rm_applicationsecuritygroup:
        resource_group: "{{ resource_group_name }}"
        name: "{{ item }}"
        location: "{{ location }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
        tags:
          environment: "test"
      loop: "{{ asg_names }}"
      register: asg_results

    # =========================================
    # ROUTE TABLE (FREE)
    # =========================================

    - name: Create route table
      azure.azcollection.azure_rm_routetable:
        resource_group: "{{ resource_group_name }}"
        name: "{{ route_table_name }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
        tags:
          environment: "test"
      register: route_table_result

    - name: Add routes to route table
      azure.azcollection.azure_rm_route:
        resource_group: "{{ resource_group_name }}"
        route_table_name: "{{ route_table_name }}"
        name: "{{ item.name }}"
        address_prefix: "{{ item.prefix }}"
        next_hop_type: "{{ item.hop }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      loop:
        - { name: "route-to-internet", prefix: "0.0.0.0/0", hop: "internet" }
        - { name: "route-internal", prefix: "10.1.0.0/16", hop: "none" }
      register: route_results

    # =========================================
    # AVAILABILITY SETS (FREE)
    # =========================================

    - name: Create availability sets
      azure.azcollection.azure_rm_availabilityset:
        resource_group: "{{ resource_group_name }}"
        name: "{{ item }}"
        location: "{{ location }}"
        platform_fault_domain_count: 2
        platform_update_domain_count: 5
        sku: "Aligned"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
        tags:
          environment: "test"
      loop: "{{ availability_set_names }}"
      register: avset_results

    # =========================================
    # PROXIMITY PLACEMENT GROUP (FREE)
    # =========================================

    - name: Create proximity placement group
      azure.azcollection.azure_rm_proximityplacementgroup:
        resource_group: "{{ resource_group_name }}"
        name: "{{ ppg_name }}"
        location: "{{ location }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
        tags:
          environment: "test"
      register: ppg_result

    # =========================================
    # QUERY ALL RESOURCES (for indirect node counting)
    # =========================================

    - name: Get resource group info
      azure.azcollection.azure_rm_resourcegroup_info:
        name: "{{ resource_group_name }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      register: rg_info

    - name: Get subscription info
      azure.azcollection.azure_rm_subscription_info:
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      register: sub_info

    - name: Get virtual network info
      azure.azcollection.azure_rm_virtualnetwork_info:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vnet_name }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      register: vnet_info

    - name: Get subnet info
      azure.azcollection.azure_rm_subnet_info:
        resource_group: "{{ resource_group_name }}"
        virtual_network_name: "{{ vnet_name }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      register: subnet_info

    - name: Get NSG info
      azure.azcollection.azure_rm_securitygroup_info:
        resource_group: "{{ resource_group_name }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      register: nsg_info

    - name: Get route table info
      azure.azcollection.azure_rm_routetable_info:
        resource_group: "{{ resource_group_name }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      register: route_info

    - name: Get availability set info
      azure.azcollection.azure_rm_availabilityset_info:
        resource_group: "{{ resource_group_name }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      register: avset_info

    - name: Get proximity placement group info
      azure.azcollection.azure_rm_proximityplacementgroup_info:
        resource_group: "{{ resource_group_name }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      register: ppg_info

    - name: Get application security group info
      azure.azcollection.azure_rm_applicationsecuritygroup_info:
        resource_group: "{{ resource_group_name }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      register: asg_info

    # =========================================
    # SUMMARY
    # =========================================

    - name: Display test summary
      ansible.builtin.debug:
        msg: |
          =====================================================
          AZURE INDIRECT NODE TEST SUMMARY
          =====================================================
          
          RESOURCES CREATED (all FREE):
            Resource Groups:           1
            Virtual Networks:          1
            Subnets:                   3
            Network Security Groups:   3
            Application Security Grps: 3
            Route Tables:              1
            Routes:                    2
            Availability Sets:         2
            Proximity Placement Grps:  1
            -----------------------------------------
            TOTAL UNIQUE RESOURCES:   17
          
          RESOURCES QUERIED (for indirect node counting):
            Resource Groups:    {{ rg_info.resourcegroups | length }}
            Subscriptions:      {{ sub_info.subscriptions | length }}
            Virtual Networks:   {{ vnet_info.virtualnetworks | length }}
            Subnets:           {{ subnet_info.subnets | length }}
            NSGs:              {{ nsg_info.securitygroups | length }}
            Route Tables:      {{ route_info.route_tables | length }}
            Availability Sets: {{ avset_info.ansible_info.azure_availabilitysets | default([]) | length }}
            PPGs:              {{ ppg_info.proximityplacementgroups | length }}
            ASGs:              {{ asg_info.applicationsecuritygroups | default([]) | length }}
          
          CLEANUP: {{ 'Resources will be deleted' if cleanup else 'Resources retained. Run with -e cleanup=true to delete.' }}
          =====================================================

    # =========================================
    # CLEANUP (Optional)
    # =========================================

    - name: Delete resource group (deletes all resources inside)
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        state: absent
        force_delete_nonempty: true
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      when: cleanup | bool
