---
# Azure Indirect Node Counting Test Playbook
# Uses only FREE resources - Resource Groups cost nothing to create/delete
#
# Prerequisites:
#   - azure.azcollection installed
#
# Authentication:
#   Pass credentials as extra variables:
#     -e azure_client_id=xxx
#     -e azure_secret=xxx
#     -e azure_subscription_id=xxx
#     -e azure_tenant=xxx
#
#   Or in AAP Job Template Extra Variables:
#     azure_client_id: "your-client-id"
#     azure_secret: "your-secret"
#     azure_subscription_id: "your-subscription-id"
#     azure_tenant: "your-tenant-id"
#
# Usage:
#   ansible-playbook azure_indirect_node_test.yml -e @azure_creds.yml
#   ansible-playbook azure_indirect_node_test.yml -e cleanup=true -e @azure_creds.yml

- name: Azure Indirect Node Counting Test
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    resource_group_name: "aap-indirect-node-test-rg"
    location: "eastus"
    cleanup: false  # Set to true to delete resources after test
    
    # Azure credentials - pass these as extra vars or from AAP credential
    # azure_client_id: ""
    # azure_secret: ""
    # azure_subscription_id: ""
    # azure_tenant: ""

  tasks:
    # =========================================
    # Resource Group Operations (FREE)
    # =========================================
    
    - name: Create resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ location }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
        tags:
          environment: "test"
          purpose: "aap-indirect-node-counting"
          created_by: "ansible"
      register: rg_result

    - name: Display resource group info
      ansible.builtin.debug:
        msg: "Created resource group: {{ rg_result.state.name }} in {{ rg_result.state.location }}"

    # =========================================
    # Gather Information (FREE)
    # =========================================

    - name: Get resource group info
      azure.azcollection.azure_rm_resourcegroup_info:
        name: "{{ resource_group_name }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      register: rg_info

    - name: Display resource group details
      ansible.builtin.debug:
        var: rg_info.resourcegroups

    # =========================================
    # Update Tags (FREE)
    # =========================================

    - name: Update resource group tags
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ location }}"
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
        tags:
          environment: "test"
          purpose: "aap-indirect-node-counting"
          created_by: "ansible"
          updated: "{{ ansible_date_time.iso8601 | default('now') }}"
          test_run: "indirect-node-validation"

    # =========================================
    # List Subscriptions (FREE)
    # =========================================

    - name: Get subscription info
      azure.azcollection.azure_rm_subscription_info:
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      register: sub_info

    - name: Display subscription
      ansible.builtin.debug:
        msg: "Subscription: {{ sub_info.subscriptions[0].display_name | default('N/A') }}"
      when: sub_info.subscriptions | length > 0

    # =========================================
    # Cleanup (Optional)
    # =========================================

    - name: Delete resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        state: absent
        force_delete_nonempty: true
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
      when: cleanup | bool

    - name: Cleanup notice
      ansible.builtin.debug:
        msg: "Resource group '{{ resource_group_name }}' retained. Run with -e cleanup=true to delete."
      when: not (cleanup | bool)
